/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  uprating,
} from './components/up-stars/up-stars';

export namespace Components {
  interface UpIcon {
    'height'?: string;
  }
  interface UpLogo {
    'height'?: string;
  }
  interface UpStars {
    'height'?: string;
    'ratings'?: uprating;
  }
}

declare global {


  interface HTMLUpIconElement extends Components.UpIcon, HTMLStencilElement {}
  const HTMLUpIconElement: {
    prototype: HTMLUpIconElement;
    new (): HTMLUpIconElement;
  };

  interface HTMLUpLogoElement extends Components.UpLogo, HTMLStencilElement {}
  const HTMLUpLogoElement: {
    prototype: HTMLUpLogoElement;
    new (): HTMLUpLogoElement;
  };

  interface HTMLUpStarsElement extends Components.UpStars, HTMLStencilElement {}
  const HTMLUpStarsElement: {
    prototype: HTMLUpStarsElement;
    new (): HTMLUpStarsElement;
  };
  interface HTMLElementTagNameMap {
    'up-icon': HTMLUpIconElement;
    'up-logo': HTMLUpLogoElement;
    'up-stars': HTMLUpStarsElement;
  }
}

declare namespace LocalJSX {
  interface UpIcon {
    'height'?: string;
  }
  interface UpLogo {
    'height'?: string;
  }
  interface UpStars {
    'height'?: string;
    'ratings'?: uprating;
  }

  interface IntrinsicElements {
    'up-icon': UpIcon;
    'up-logo': UpLogo;
    'up-stars': UpStars;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'up-icon': LocalJSX.UpIcon & JSXBase.HTMLAttributes<HTMLUpIconElement>;
      'up-logo': LocalJSX.UpLogo & JSXBase.HTMLAttributes<HTMLUpLogoElement>;
      'up-stars': LocalJSX.UpStars & JSXBase.HTMLAttributes<HTMLUpStarsElement>;
    }
  }
}


